services:
  db:
    image: mysql:8.0
    container_name: academy-connect
    ports:
      - 9911:3306 # MySQL 포트를 환경 변수로 관리
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: academy-connect
    volumes:
      - academy-connect-data:/var/lib/mysql
    networks:
      - academy-connect-network

volumes:
  academy-connect-data:

networks:
  academy-connect-network:
    driver: bridge