server:
  port: 8080


spring:
  application:
    name: academy-connect
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: ${DB_URL:jdbc:log4jdbc:mysql://localhost:3306/academy_connect}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:create}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${DB_FORMAT_SQL:true}
        use_sql_comments: ${DB_USE_SQL_COMMENTS:true}